user: www-data

listen:
  - port: 80
  - port: 443
    ssl:
      certificate-file: /h2o/localhost.crt
      key-file: /h2o/localhost.key
      ocsp-update-interval: 0

hosts:
  "*":
    paths:
      "/h2oresponse":
              mruby.handler: |
                Proc.new do |env|
                  [200, {'content-type' => 'text/html; charset=utf-8'}, ['Hello World!']]
                end
      "/":

        file.dir: !env PUBLIC_FOLDER

        redirect:
          url: /index.php/
          internal: YES
          status: 307

file.custom-handler:
  extension: .php
  fastcgi.connect:
    host: php
    port: 9000
    type: tcp

access-log: /dev/null
error-log: /dev/stderr
pid-file: /h2o/pid-file
