FROM php:8.1-fpm

ARG PHP_VERSION=8.1
ARG ENVIRONMENT=dev

# Install dependencies and PHP extensions
RUN apt-get update && apt-get install -y \
    mc \
    htop \
    libzip-dev \
    gettext \
    libtidy-dev \
    && docker-php-ext-install gettext pdo_mysql zip tidy \
    && pecl install xdebug-3.3.2 redis-6.0.2 \
    && docker-php-ext-enable redis xdebug \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Configure PHP
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

ENV XDEBUG_FILE_LINK_FORMAT='phpstorm://open?file=%f&line=%l'
COPY ./99-radaptor-dev.ini "$PHP_INI_DIR/conf.d/99-radaptor-dev.ini"

# Install Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR /app
