xdebug.mode=debug,profile,develop,trace,coverage
;xdebug.mode=debug,develop

xdebug.start_with_request=trigger

xdebug.output_dir=/app/.profiler
xdebug.scream=0
xdebug.profiler_output_name=profiler/%R.cachegrind.out
xdebug.discover_client_host=false
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=PHPSTORM

xdebug.collect_return=true
xdebug.collect_assignments=true
xdebug.collect_params = true
xdebug.trace_format=1
xdebug.trace_options=2|8
xdebug.trace_output_name=trace/%R.tsv

xdebug.use_compression=false
xdebug.force_display_errors=1

xdebug.file_link_format=${XDEBUG_FILE_LINK_FORMAT}

xdebug.show_local_vars=1

xdebug.var_display_max_data=-1
xdebug.var_display_max_depth=-1
xdebug.var_display_max_children=-1

error_log = /app/.logs/php_errors.log
log_errors = On
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
date.timezone = UTC

