name: php84
services:
  web:
    build:
      context: ./h2o
      dockerfile: Dockerfile
    restart: always
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./h2o.conf:/config/h2o.conf
      - ../:/app
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./php8.4/Dockerfile
    working_dir: /app
    volumes:
      - ../:/app
