user: www-data

listen:
  - port: 80
  - port: 443
    ssl:
      certificate-file: /h2o/localhost.crt
      key-file: /h2o/localhost.key
      ocsp-update-interval: 0

hosts:
  "*":
    paths:
      "/h2oresponse":
              mruby.handler: |
                Proc.new do |env|
                  [200, {'content-type' => 'text/html; charset=utf-8'}, ['Hello World!']]
                end
      "/":
        mruby.handler: |
          redis = H2O::Redis.new(host: 'redis', port: 6379)

          Proc.new do |env|

            # Check for the existence of the PHPSESSID cookie to determine if there's an active PHP session
            cookies = (env["HTTP_COOKIE"] || "").split(';').map(&:strip).map { |cookie| cookie.split('=', 2) }.to_h
            if cookies["PHPSESSID"]
              # If PHPSESSID exists, pass the request to the next handler (PHP) as there might be a logged-in user
              [399, {}, []]
            end

            # Given that there was no session, we can be sure that the user is not logged in
            tmp_userid = -1

            # Construct the cache key based on public access
            request_uri = env["PATH_INFO"] + (env["QUERY_STRING"].empty? ? "" : "?#{env["QUERY_STRING"]}")
            cache_key = "user:#{tmp_userid}:REQUEST_URI:#{request_uri}"

            # Check if the page is in Redis cache
            if env["REQUEST_METHOD"] == "GET"
              if redis.exists(cache_key).join == 1
                headers = {
                  "content-type" => "text/html",
                  "content-encoding" => "br",  # Specify that the content is Brotli-compressed
                  "X-Cache-Status" => "Hit H2O-redis"
                }
                [200, headers, [redis.get(cache_key).join]]
              else
                [399, {}, []]  # Pass handling to the next handler if not found in cache
              end
            else
              [399, {}, []]  # Non-GET requests are passed to the next handler
            end
          end

        file.dir: !env PUBLIC_FOLDER

        redirect:
          url: /index.php/
          internal: YES
          status: 307

file.custom-handler:
  extension: .php
  fastcgi.connect:
    host: php
    port: 9000
    type: tcp

access-log: /dev/null
error-log: /dev/stderr
pid-file: /h2o/pid-file
