FROM php:8.3-fpm

ARG PHP_VERSION=8.3
ARG ENVIRONMENT=dev

# Install dependencies and PHP extensions
RUN apt-get update && apt-get install -y \
    mc \
    htop \
    libzip-dev \
    gettext \
    libtidy-dev \
    libbrotli-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    wget \
    gnupg

RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gettext pdo_mysql zip tidy gd calendar

RUN pecl install xdebug-3.3.2 redis-6.0.2 brotli && docker-php-ext-enable redis xdebug brotli
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Configure PHP
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# Set memory limit to -1
RUN echo "memory_limit=-1" > "$PHP_INI_DIR/conf.d/memory-limit.ini"

ENV XDEBUG_FILE_LINK_FORMAT='phpstorm://open?file=%f&line=%l'
COPY ./99-radaptor-dev.ini "$PHP_INI_DIR/conf.d/99-radaptor-dev.ini"

# Install Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Install Phive
RUN wget -O phive.phar https://phar.io/releases/phive.phar \
    && wget -O phive.phar.asc https://phar.io/releases/phive.phar.asc \
    && gpg --keyserver hkps://keys.openpgp.org --recv-keys 0x9D8A98B29B2D5D79 \
    && gpg --verify phive.phar.asc phive.phar \
    && chmod +x phive.phar \
    && mv phive.phar /usr/local/bin/phive

# Automatically trust and install specified phars using Phive
COPY ./phars.xml /app/.phive/phars.xml
RUN phive install
ENV PATH="/app/tools:/app/vendor/bin:$PATH"

COPY ../radaptor /usr/local/bin/radaptor
RUN chmod +x /usr/local/bin/radaptor

ENV RADAPTOR_APP_ROOT=/app
WORKDIR /app
