<?php

/**
 * Class ApplicationConfig.
 *
 * This class contains configuration constants for the application.
 * It should not be used directly to access configuration values. Instead, all
 * accesses should be routed through the Config enum to ensure that the
 * application can correctly handle overrides from environment variables.
 *
 * Usage of this class directly is discouraged and considered against best
 * practices. Instead, refer to the Config enum for fetching configuration values.
 *
 * Example Usage:
 * ---------------
 * To retrieve the database host, you should not use:
 *   - `$host = ApplicationConfig::DB_HOST;`
 *
 * Instead, use:
 *   - `$host = Config::DB_HOST->value();`
 *
 * This approach ensures that the configuration is fetched correctly with the
 * ability to override via environment variables.
 *
 * @see Config For accessing the configuration values safely and effectively.
 */
class ApplicationConfig
{
	/**
	 * Development settings.
	 */
	public const bool DEV_DEVELOPERS_CAN_ACCESS_ALL_RESOURCES = true;
	public const bool DEV_WEBPAGE_AUTOGENERATION_ON_WIDGET_REQUEST = true;
	public const bool DEV_CONSOLEWRITER = false;
	public const bool DEV_ENABLE_TIDY_OUTPUT = false;
	public const bool DEV_APP_DEBUG_INFO = true;
	public const bool DEV_APP_MINIFY_HTML = false;

	/**
	 * Application settings.
	 */
	public const string APP_APPLICATION_IDENTIFIER = 'RadaptorPortal';
	public const string APP_SITE_NAME = 'Radaptor Portal';
	public const string APP_DOMAIN_CONTEXT = 'localhost';
	public const string APP_DEFAULT_THEME_NAME = 'RadaptorPortalAdmin';
	public const string APP_FORM_DEFAULT_TEMPLATE = 'autogenerated';
	public const bool APP_PERSISTENT_CACHE_ENABLED = false;
	public const bool APP_DISABLE_SEO_URL = false;            // Disable SEO-friendly path generation by the URL helper
	public const string APP_BOOTSTRAP_ADMIN_USERNAME = 'admin';
	public const string APP_BOOTSTRAP_ADMIN_PASSWORD = 'admin123456';
	public const string APP_BOOTSTRAP_ADMIN_LOCALE = 'en_US';
	public const string APP_BOOTSTRAP_ADMIN_TIMEZONE = 'UTC';

	/**
	 * Database settings.
	 */
	public const string DB_DEFAULT_DSN = 'mysql:host=mariadb;port=3306;user=root;password=radaptor_portal;dbname=radaptor_portal';
	public const bool DB_AUDIT_ENABLE_ANONYMOUS = true;

	/**
	 * Path settings.
	 */
	public const string LINUX_FILE_GROUP = 'www-data';
	public const string LINUX_FILE_OWNER = 'www-data';
	public const int LINUX_FILE_MODE = 0o666;
	public const int LINUX_FILE_MODE_DIRECTORY = 0o777;
	public const string PATH_GENERATED_WEBPAGES_DIRECTORY = '__generated_webpages__';
	public const string PATH_IMAGE_CACHE_LOCAL_SUBFOLDER = 'public/_www_static/cache/';
	public const string PATH_ICONS_EXTENSION = '.png';
	public const string PATH_AJAX_LOADER_HTML = '<div style="text-align:center;margin:30px;"><img src="/assets/_common/media/ajax-loader.gif" alt="" /></div>';
	public const string PATH_CDN = '/assets/';
	public const string PATH_IMAGE_CACHE_URL = '/assets/_common/cache/';
	public const string PATH_ICONS = '/assets/_common/ico/';
	public const string PATH_PUBLIC_SITE_ROOT = '';
	public const string PATH_FONTS_DIRECTORY = '';
	public const string PATH_UPLOADED_FILES_DIRECTORY = 'uploaded_files/';
	public const string PATH_UPLOADING_TEMPORARY_DIRECTORY = 'uploaded_files/_tmp_/';
	public const string PATH_UPLOADING_TEMPORARY_PARTITIONS_DIRECTORY = 'uploaded_files/_tmp_/_partitions_/';

	/**
	 * Email settings.
	 */
	public const string EMAIL_HOST = '';
	public const string EMAIL_PORT = '';
	public const string EMAIL_USERNAME = '';
	public const string EMAIL_PASSWORD = '';
	public const string EMAIL_TO_ADDRESS = '';
	public const string EMAIL_FROM_ADDRESS = '';
	public const string EMAIL_FROM_NAME = '';
	public const bool EMAIL_FORCE_CATCHER_IN_NON_PROD = true;
	public const string EMAIL_CATCHER_HOST = 'mailpit';
	public const int EMAIL_CATCHER_SMTP_PORT = 1025;
	public const string EMAIL_SMTP_HOST = '';
	public const int EMAIL_SMTP_PORT = 587;
	public const string EMAIL_SMTP_USERNAME = '';
	public const string EMAIL_SMTP_PASSWORD = '';
	public const bool EMAIL_SMTP_USE_STARTTLS = true;
	public const string EMAIL_SMTP_EHLO_HOST = '';
	public const int EMAIL_QUEUE_WORKER_SLEEP_MS = 500;
	public const int EMAIL_QUEUE_MAX_ATTEMPTS = 5;
	public const int EMAIL_QUEUE_ARCHIVE_TTL_DAYS = 30;
	public const int EMAIL_QUEUE_DEAD_LETTER_TTL_DAYS = 180;
	public const int EMAIL_QUEUE_RESERVATION_TIMEOUT_SECONDS = 300;
	public const int EMAIL_QUEUE_PURGE_INTERVAL_SECONDS = 300;

	/**
	 * Generator settings.
	 */
	public const string GENERATED_AUTOLOADER_FILE = 'generated/__autoload__.php';
	public const string GENERATED_DB_FILE = 'generated/__db_schema_data__.php';
	public const string GENERATED_LAYOUTS_FILE = 'generated/__layout_types__.php';
	public const string GENERATED_TEMPLATES_FILE = 'generated/__templates__.php';
	public const string GENERATED_TEST_TEMPLATES_FILE = 'generated/__test_templates__.php';
	public const string GENERATED_THEMED_TEMPLATES_FILE = 'generated/__themed_templates__.php';
	public const string GENERATED_WIDGETS_FILE = 'generated/__widgets__.php';
	public const string GENERATED_THEME_DATA_FILE = 'generated/__theme_data__.php';
	public const string GENERATED_FORMS_FILE = 'generated/__forms__.php';
	public const string GENERATED_IMPORT_EXPORT_DATASETS_FILE = 'generated/__import_export_datasets__.php';
	public const string GENERATED_ROLES_FILE = 'generated/__roles__.php';
	public const string GENERATED_PLUGINS_FILE = 'generated/__plugins__.php';
	public const string GENERATED_BROWSER_EVENT_DOCS_FILE = 'generated/__browser_event_docs__.php';
	public const string GENERATED_CONFIG_FILE = 'generated/__config__.php';
	public const string GENERATED_TEMPLATE_RENDERERS_FILE = 'generated/__template_renderers__.php';
	public const array GENERATOR_IGNORED_FOLDERS = [
		'/docker',
		'/tests',
		'/tools/',
		'/public/',
		'/vendor/',
	];
}
