<?php

/**
 * Fixture for the users table.
 *
 * References: @users.{username}
 * Example: @users.admin_developer
 */
class FixtureUsers extends AbstractFixture
{
	// Password hash for 'password123' generated by User::encodePassword() (includes app pepper)
	private const string PASSWORD_HASH = '$2y$12$yCEteEppXB1m0cg5wg/GheQDHl6AfdNzRoXFPCCFvQilvCWHwn.o6';

	public function getTableName(): string
	{
		return 'users';
	}

	public function getReferenceBy(): string
	{
		return 'username';
	}

	/**
	 * @return list<array{
	 *     username: string,
	 *     password: string,
	 *     is_active: int
	 * }>
	 */
	public function getData(): array
	{
		return [
			['username' => 'admin_developer', 'password' => self::PASSWORD_HASH, 'is_active' => 1],
			['username' => 'user_noroles', 'password' => self::PASSWORD_HASH, 'is_active' => 1],
			['username' => 'admin_inactive', 'password' => self::PASSWORD_HASH, 'is_active' => 0],
			['username' => 'developer_user_new_theme', 'password' => self::PASSWORD_HASH, 'is_active' => 1],
			['username' => 'developer_user_old_theme', 'password' => self::PASSWORD_HASH, 'is_active' => 1],
		];
	}
}
