FROM php:7.4-fpm-alpine

RUN apk add --no-cache --virtual .build-deps \
    $PHPIZE_DEPS

RUN apk add --no-cache gettext-dev tidyhtml-dev

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

RUN pecl install xdebug-3.1.6
RUN pecl install redis-6.0.2

RUN docker-php-ext-install gettext pdo_mysql tidy

RUN docker-php-ext-enable redis xdebug

RUN apk del .build-deps

COPY ./99-radaptor-dev.ini "$PHP_INI_DIR/conf.d/99-radaptor-dev.ini"

RUN echo "mbstring.internal_encoding=UTF-8" >> "$PHP_INI_DIR/conf.d/mbstring.ini"
